$(document).ready ->

  App.room = App.cable.subscriptions.create({
    channel: 'RoomChannel'
    chat_room_id: $('#messages_list').data('chat-room-id')
    user_id: $('#messages_list').data('user-id')
    test: "teststst"
  },
    connected: ->
    disconnected: ->
    received: (data) ->
      $('#messages_list').append data['message']
      $("html,body").animate({ scrollTop: $('#messages_list').prop("scrollHeight") }, "fast");
      $('#message_input').focus()
    speak: (message, chat_room_id, user_id) ->
      @perform 'speak',
        message: message
        chat_room_id: chat_room_id
        user_id: user_id
  )
  $(document).on 'keypress', '[data-behavior~=room_speaker]', (event) ->
    if event.keyCode == 13
      App.room.speak event.target.value, $('#messages_list').data('chat-room-id'), $('#messages_list').data('user-id')
      event.target.value = ''
      return event.preventDefault()
    return

# ---
# generated by js2coffee 2.2.0